CREATE TYPE "member_status" AS ENUM (
  'active',
  'inactive',
  'suspended'
);

CREATE TYPE "membership_tier" AS ENUM (
  'bronze',
  'silver',
  'gold',
  'platinum'
);

CREATE TYPE "payment_method" AS ENUM (
  'cash',
  'card',
  'gcash',
  'others'
);

CREATE TYPE "pay_status" AS ENUM (
  'paid',
  'pending',
  'failed'
);

CREATE TYPE "specialization" AS ENUM (
  'strength_training',
  'cardio',
  'yoga',
  'pilates',
  'zumba',
  'crossfit',
  'boxing',
  'martial_arts',
  'swimming',
  'nutrition_coaching',
  'physical_therapy',
  'general_fitness'
);

CREATE TYPE "attendance_status" AS ENUM (
  'present',
  'absent',
  'cancelled'
);

CREATE TYPE "weekday" AS ENUM (
  'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'
);

CREATE TABLE "Members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar,
  "phone_number" varchar,
  "date_of_birth" date,
  "join_date" date,
  "status" member_status
);

CREATE TABLE "Memberships" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "start_date" date,
  "end_date" date,
  "is_active" boolean,
  "tier" membership_tier
);

CREATE TABLE "Payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "membership_id" int NOT NULL,
  "amount" dec(10,2),
  "payment_date" date,
  "method" payment_method,
  "status" pay_status
);

CREATE TABLE "Trainers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "spec" specialization,
  "phone_number" varchar,
  "hire_date" date
);

CREATE TABLE "Classes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_name" varchar,
  "trainer_id" int NOT NULL,
  "schedule_day" weekday,
  "start_time" time,
  "end_time" time,
  "capacity" int
);

CREATE TABLE "Attendance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "class_id" int NOT NULL,
  "attendance_date" date,
  "status" attendance_status
);

ALTER TABLE "Memberships" ADD FOREIGN KEY ("member_id") REFERENCES "Members" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Payments" ADD FOREIGN KEY ("membership_id") REFERENCES "Memberships" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Classes" ADD FOREIGN KEY ("trainer_id") REFERENCES "Trainers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Attendance" ADD FOREIGN KEY ("member_id") REFERENCES "Members" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Attendance" ADD FOREIGN KEY ("class_id") REFERENCES "Classes" ("id") DEFERRABLE INITIALLY IMMEDIATE;
